### PR TITLE
Added APP_NAME and NODE_ENV to app.js config file

### PR DESCRIPTION
**Pull request by eNzyOfficial**
Similar to Laravel, I've added APP_NAME and NODE_ENV to the app.js config file.

Including APP_NAME, allows an easy way to have the name of an app consistent throughout the app, rather than having to hard code it in.

NODE_ENV removes the need to potentially `use` both `Env` and `Config` and condenses it down into just `Config`. A niche use case, but a use case none the less!

Any problems, or suggestions, I'm all ears!

Thanks again for the great framework! 💯

### CODE REVIEW

**Comment by eNzyOfficial** [comment]
If this gets approved and you want me to run this through fullstack, slim and api, I'll be happy to create pull requests for them! :)

**Comment by thetutlage** [comment]
`APP_NAME` is fine but `NODE_ENV` cannot be added to the config file and here's why.

When you move a configuration to `config` files, then every part of your app will be relying on it. Which also means if I remove `NODE_ENV` from the `.env` file, then the app should work fine, since it's declared in the config directory.

This will result in bad and unwanted behavior. A bunch of Node.js modules internally rely on `NODE_ENV` and it's part of the Node.js Eco-system

**Comment by eNzyOfficial** [comment]
You bring up a valid point that I hadn't even considered, I'll strip out the NODE_ENV stuff now, thanks!

**Comment by RomainLanz** [comment]
Hey !

The description is exactly the same as Laravel (https://github.com/laravel/laravel/blob/master/config/app.php#L10).

It's not relevant to Adonis (like we don't have notification). Could be great to rephrase it.

**Comment by eNzyOfficial** [comment]
Yeah sorry, I'm using a 3rd party package for notifications, and it didn't click. I shall rewrite it now!

**Comment by RomainLanz** [comment]
Actually, this is the old repository of Adonis.

Please, send the same PR to new Adonis blueprint.

- https://github.com/adonisjs/adonis-fullstack-app
- https://github.com/adonisjs/adonis-api-app
- https://github.com/adonisjs/adonis-slim-app

**Pull request closed without merging**
